name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Haetaan lähdekoodit reposta.
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Asennetaan Node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Asennetaan projektin riippuvuudet.
      - name: Install dependencies
        run: npm install

      # 4. Buildataan projekti.
      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
          VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
          VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
          VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
          VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VITE_FIREBASE_MESSAGINGSENDERID }}
          VITE_FIREBASE_APPID: ${{ secrets.VITE_FIREBASE_APPID }}

      # 5. Julkaistaan Web App -palveluun.
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: omabudjetti-d
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
